apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: getting-started-with-aws
  annotations:
    uxp-guide: getting-started
spec:
  crossplane:
    version: ">=v1.2.1-0"
  dependsOn:
    - provider: registry.upbound.io/crossplane/provider-aws
      version: ">=v0.22.0-0"
